<?php

namespace AppBundle\Repository;

/**
 * SocioprofessionalGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocioprofessionalGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
